sequenceDiagram
autonumber

participant УГЗ as УГЗ ЕИС
participant КШД as КШД ЕИС
participant ЭБ as ЭБ (ГИИС Электронный бюджет)
participant ЕИС as ЕИС

rect rgb(230, 240, 255)
УГЗ->>КШД: Предложение для включения в ПГЗ
КШД->>ЭБ: Передача предложения для включения в ПГЗ
ЭБ-->>КШД: Подтверждение приема предложения (НомерЭБ)
КШД-->>УГЗ: Подтверждение приема предложения (НомерЭБ)
end

rect rgb(240, 245, 255) 
    УГЗ->>КШД: Запрос состояния предложения (НомерЭБ)
    КШД->>ЭБ: Запрос состояния предложения (НомерЭБ)
    ЭБ-->>КШД: Ответ КБК и Статус предложения (НомерЭБ)
    КШД-->>УГЗ: Текущий статус предложения с КБК (НомерЭБ)
end

rect rgb(250, 250, 255)
УГЗ->>КШД: Проект план-графика  
КШД->>ЭБ: Передача проекта план-графика 
ЭБ-->>КШД: Подтверждение приема план-графика (НомерЭБ)
КШД-->>УГЗ: Подтверждение приема план-графика (НомерЭБ)
end

%% на ЕИС из ЭБ автоматически
%% rect rgba(227, 227, 227, 1)
%% ЭБ->>ЕИС: План-график (автоматически)
%% получаем ли номер ЕИС?
%% end

rect rgb(200, 220, 255)
УГЗ->>КШД: Запрос статуса план-графика (НомерЭБ) 
КШД->>ЕИС: Запрос статуса план-графика (НомерЭБ) 
ЕИС-->>КШД: Ответ Статус план-графика (НомерЕИС)
КШД-->>УГЗ: Текущий статус план-графика (НомерЕИС)
end
