sequenceDiagram
    participant УГЗ as УГЗ ЕИС
    participant ЕИС as ЕИС
    participant ГОЗ as АСТ ГОЗ
    
    
    rect rgb(255, 250, 200)
        УГЗ->>ЕИС: 2.1 Закупочная процедура (Приглашение)
        ЕИС-->>УГЗ: 2.1a Подтверждение получения       
    end
    
    rect rgba(227, 227, 227, 1)
        alt Закупка закрытого типа
            ЕИС->>ГОЗ: 2.2 Приглашение (автоматически)
            ГОЗ-->>ЕИС: 2.2a Подтверждение получения
        end
    end
    
    rect rgb(255, 240, 180)
       opt Закупка открытого типа
        loop Мониторинг статуса в ЕИС
            УГЗ->>ЕИС: 2.3 Запрос состояния закупочной процедуры
            alt Процедура активна
                ЕИС-->>УГЗ: 2.3a Статус Прием заявок
            else Процедура завершена
                ЕИС-->>УГЗ: 2.3b Статус Завершена
            else Процедура приостановлена
                ЕИС-->>УГЗ: 2.3c Статус Приостановлена
            end
            УГЗ->>ЕИС: 2.3 Протокол отмены закупочной процедуры
            ЕИС-->>УГЗ: 2.3c Статус Отменена
        end
        end
    end
    
    rect rgb(255, 235, 170)
        opt Закупка закрытого типа
            loop Мониторинг статуса в ГОЗ
                УГЗ->>ГОЗ: 2.4 Запрос состояния закупочной процедуры
                alt Процедура в ГОЗ активна
                    ГОЗ-->>УГЗ: 2.4a Статус Прием заявок в ГОЗ
                else Процедура в ГОЗ завершена
                    ГОЗ-->>УГЗ: 2.4b Статус Завершена в ГОЗ
                else Ошибка в ГОЗ
                    ГОЗ-->>УГЗ: 2.4c Статус Ошибка
                end
            end
        end
    end
    
    rect rgb(255, 230, 160)
        alt Определениие победителя на ЕИС
            УГЗ->>ЕИС: 2.5a Протокол выбора победителя
            ЕИС-->>УГЗ: 2.5b Подтверждение приема протокола выбора победителя
        else Требуется дополнительная оценка
            УГЗ->>ЕИС: 2.5c Запрос дополнительной информации
            ЕИС-->>УГЗ: 2.5d Прием и обработка дополнительной информации
        end
    end

    rect rgb(255, 230, 160)
        alt Определениие победителя на АСТ ГОЗ
            УГЗ->>ГОЗ: 2.6a Протокол выбора победителя
            ГОЗ-->>УГЗ: 2.6b Подтверждение приема протокола выбора победителя
        else На ЭТП размещены дополнительные запросы
           ГОЗ-->>УГЗ: 2.5c Запрос на разъяснение результатов закупки
            УГЗ->>ГОЗ: 2.6d Разъяснение результатов закупки
            ГОЗ-->>УГЗ: 2.5e Запрос на предоставление документации
            УГЗ->>ГОЗ: 2.6f Протокол о рассмотрении запроса на предоставление документации
            ГОЗ-->>УГЗ: 2.5g Запрос на разъяснение положений документации
            УГЗ->>ГОЗ: 2.6h Разъяснение положений документации
        end
    end
    
    rect rgb(255, 225, 150)
        УГЗ->>ЕИС: 2.7 Финализация закупочной процедуры
        alt Процедура успешно завершена
            ЕИС-->>УГЗ: 2.7a Подтверждение завершения
        else Требуются исправления
            ЕИС-->>УГЗ: 2.7b Список замечаний
            УГЗ->>ЕИС: 2.7c Исправленная процедура
        end
    end
