sequenceDiagram
autonumber

participant УГЗ as УГЗ ЕИС
participant КШД as КШД ЕИС
participant ЕИС as ЕИС
participant АСТ as АСТ ГОЗ


rect rgb(240, 255, 240)
УГЗ->>КШД: Передача проекта госконтракта 
КШД->>ЕИС: Передача проекта госконтракта 
ЕИС-->>КШД: Подтверждение приема проекта госконтракта (НомерЕИС)
КШД-->>УГЗ: Подтверждение приема проекта госконтракта (НомерЕИС)
%% передается ли проект на АСТ? нужно ли изменение итогового статуса на ЕИС?
end

rect rgb(230, 250, 230)
%% идет напрямую на АСТ? номерАСТ получаем тогда доп.запросом мониторинга с ЕИС?
УГЗ->>КШД: Передать госконтракт на подписание (НомерЕИС)
КШД->>АСТ: Передача госконтракта на подписание (НомерЕИС)
АСТ-->>КШД: Подтверждение приема госконтракта (НомерАСТ)
КШД-->>УГЗ: Подтверждение приема госконтракта (НомерАСТ)
end

rect rgb(220, 245, 220)
УГЗ->>КШД: Запрос состояния госконтракта (НомерАСТ)
КШД->>АСТ: Запрос состояния госконтракта (НомерАСТ)
АСТ-->>КШД: Текущий статус госконтракта (НомерАСТ)
АСТ-->>КШД: Протокол разногласий (файл) (НомерАСТ)
КШД-->>УГЗ: Текущий статус госконтракта (НомерАСТ)
%% при наличии протокола его также в рамках запроса получаем
КШД-->>УГЗ: Протокол разногласий (файл) (НомерАСТ)
end

rect rgb(220, 245, 220)
%% есть в функциональной схеме. Направляется только на ЕИС? нужен ли номер закупки на АСТ, от которой уклонился участник?
opt Если участник уклоняется от участия
УГЗ->>КШД: Протокол признания участника уклонившимся (НомерЕИС,НомерАСТ)
КШД->>ЕИС: Протокол признания участника уклонившимся (НомерЕИС,НомерАСТ)
ЕИС-->>КШД: Подтверждение приема протокола (НомерЕИС)
КШД-->>УГЗ: Подтверждение приема протокола (НомерЕИС)
end
end